// Generated by frontend/scripts/generate-api-contract-types.mjs from backend/openapi.json.
// Do not edit by hand.

import type { ApiResponse } from './api.types';

export type ApiContractPath =
  | '/admin/audit-logs'
  | '/admin/dashboard'
  | '/admin/languages'
  | '/admin/languages/template'
  | '/admin/permissions'
  | '/admin/roles'
  | '/admin/roles/{id}'
  | '/admin/sessions'
  | '/admin/sessions/{id}'
  | '/admin/system/health'
  | '/admin/system/metrics'
  | '/admin/uploads'
  | '/admin/uploads/{id}'
  | '/admin/users'
  | '/admin/users/{id}'
  | '/admin/users/{id}/roles'
  | '/admin/users/{id}/status'
  | '/auth/change-password'
  | '/auth/forgot-password'
  | '/auth/login'
  | '/auth/logout'
  | '/auth/refresh-token'
  | '/auth/register'
  | '/auth/resend-verification'
  | '/auth/reset-password'
  | '/auth/verify-email'
  | '/i18n/languages'
  | '/i18n/languages/{code}'
  | '/notifications'
  | '/notifications/read-all'
  | '/notifications/unread-count'
  | '/notifications/{id}'
  | '/notifications/{id}/read'
  | '/uploads'
  | '/uploads/avatar'
  | '/uploads/{id}'
  | '/users/me'
  | '/users/me/avatar'
  | '/users/me/password'
  | '/users/me/sessions'
  | '/users/me/sessions/{id}';

export const apiContractPaths = [
  "/admin/audit-logs",
  "/admin/dashboard",
  "/admin/languages",
  "/admin/languages/template",
  "/admin/permissions",
  "/admin/roles",
  "/admin/roles/{id}",
  "/admin/sessions",
  "/admin/sessions/{id}",
  "/admin/system/health",
  "/admin/system/metrics",
  "/admin/uploads",
  "/admin/uploads/{id}",
  "/admin/users",
  "/admin/users/{id}",
  "/admin/users/{id}/roles",
  "/admin/users/{id}/status",
  "/auth/change-password",
  "/auth/forgot-password",
  "/auth/login",
  "/auth/logout",
  "/auth/refresh-token",
  "/auth/register",
  "/auth/resend-verification",
  "/auth/reset-password",
  "/auth/verify-email",
  "/i18n/languages",
  "/i18n/languages/{code}",
  "/notifications",
  "/notifications/read-all",
  "/notifications/unread-count",
  "/notifications/{id}",
  "/notifications/{id}/read",
  "/uploads",
  "/uploads/avatar",
  "/uploads/{id}",
  "/users/me",
  "/users/me/avatar",
  "/users/me/password",
  "/users/me/sessions",
  "/users/me/sessions/{id}"
] as const satisfies readonly ApiContractPath[];

export type ApiContractResponse = ApiResponse<unknown>;
export type ApiContractResponses = Record<ApiContractPath, ApiContractResponse>;
