// Generated by frontend/scripts/generate-api-contract-types.mjs from backend/openapi.json.
// Do not edit by hand.

import type { ApiResponse } from './api.types';

export type ApiContractPath =
  | '/admin/audit-logs'
  | '/admin/clients'
  | '/admin/clients/financial-movements'
  | '/admin/clients/special-prices'
  | '/admin/clients/special-prices/bulk-delete'
  | '/admin/clients/special-prices/{specialPriceId}'
  | '/admin/clients/{id}'
  | '/admin/clients/{id}/levels'
  | '/admin/clients/{id}/levels/generate'
  | '/admin/clients/{id}/levels/{levelId}'
  | '/admin/clients/{id}/movements'
  | '/admin/clients/{id}/open-credit'
  | '/admin/clients/{id}/special-prices'
  | '/admin/clients/{id}/special-prices/bulk-delete'
  | '/admin/dashboard'
  | '/admin/languages'
  | '/admin/languages/template'
  | '/admin/permissions'
  | '/admin/roles'
  | '/admin/roles/{id}'
  | '/admin/sessions'
  | '/admin/sessions/{id}'
  | '/admin/settings/apis'
  | '/admin/settings/apis/gift-card-providers-2/simulate'
  | '/admin/settings/apis/gift-card-providers/simulate'
  | '/admin/settings/apis/social-media-service-providers/simulate'
  | '/admin/settings/apis/sync-all'
  | '/admin/settings/apis/temporary-number-coding-sites/simulate'
  | '/admin/settings/apis/{id}'
  | '/admin/settings/apis/{id}/sync'
  | '/admin/settings/currencies'
  | '/admin/settings/currencies/{id}'
  | '/admin/settings/payment-codes'
  | '/admin/settings/payment-codes/journal'
  | '/admin/settings/payment-codes/{id}'
  | '/admin/settings/payment-gateways'
  | '/admin/settings/payment-gateways/{id}'
  | '/admin/settings/pricing-simulation/calculate'
  | '/admin/stocks/categories'
  | '/admin/stocks/categories/{id}'
  | '/admin/stocks/product-groups'
  | '/admin/stocks/product-requirements'
  | '/admin/stocks/product-requirements/{id}'
  | '/admin/stocks/products'
  | '/admin/stocks/products/import'
  | '/admin/stocks/products/import/preview'
  | '/admin/stocks/products/{id}'
  | '/admin/stocks/products/{id}/api-connections'
  | '/admin/stocks/products/{id}/api-connections/{connectionId}'
  | '/admin/stocks/products/{id}/api-connections/{connectionId}/activate'
  | '/admin/stocks/promotions'
  | '/admin/stocks/promotions/usages'
  | '/admin/stocks/promotions/{id}'
  | '/admin/stocks/service-groups'
  | '/admin/stocks/service-groups/{id}'
  | '/admin/stocks/services'
  | '/admin/stocks/services/{id}'
  | '/admin/stocks/warehouses'
  | '/admin/stocks/warehouses/items'
  | '/admin/stocks/warehouses/items/import'
  | '/admin/stocks/warehouses/{id}'
  | '/admin/system/health'
  | '/admin/system/metrics'
  | '/admin/uploads'
  | '/admin/uploads/{id}'
  | '/admin/users'
  | '/admin/users/{id}'
  | '/admin/users/{id}/roles'
  | '/admin/users/{id}/status'
  | '/auth/2fa/disable'
  | '/auth/2fa/enable'
  | '/auth/2fa/setup'
  | '/auth/2fa/verify-login'
  | '/auth/change-password'
  | '/auth/forgot-password'
  | '/auth/login'
  | '/auth/logout'
  | '/auth/refresh-token'
  | '/auth/register'
  | '/auth/resend-verification'
  | '/auth/reset-password'
  | '/auth/verify-email'
  | '/i18n/languages'
  | '/i18n/languages/{code}'
  | '/notifications'
  | '/notifications/read-all'
  | '/notifications/unread-count'
  | '/notifications/{id}'
  | '/notifications/{id}/read'
  | '/payment-codes/redeem'
  | '/settings/app'
  | '/uploads'
  | '/uploads/avatar'
  | '/uploads/{id}'
  | '/users/me'
  | '/users/me/avatar'
  | '/users/me/password'
  | '/users/me/sessions'
  | '/users/me/sessions/{id}';

export const apiContractPaths = [
  "/admin/audit-logs",
  "/admin/clients",
  "/admin/clients/financial-movements",
  "/admin/clients/special-prices",
  "/admin/clients/special-prices/bulk-delete",
  "/admin/clients/special-prices/{specialPriceId}",
  "/admin/clients/{id}",
  "/admin/clients/{id}/levels",
  "/admin/clients/{id}/levels/generate",
  "/admin/clients/{id}/levels/{levelId}",
  "/admin/clients/{id}/movements",
  "/admin/clients/{id}/open-credit",
  "/admin/clients/{id}/special-prices",
  "/admin/clients/{id}/special-prices/bulk-delete",
  "/admin/dashboard",
  "/admin/languages",
  "/admin/languages/template",
  "/admin/permissions",
  "/admin/roles",
  "/admin/roles/{id}",
  "/admin/sessions",
  "/admin/sessions/{id}",
  "/admin/settings/apis",
  "/admin/settings/apis/gift-card-providers-2/simulate",
  "/admin/settings/apis/gift-card-providers/simulate",
  "/admin/settings/apis/social-media-service-providers/simulate",
  "/admin/settings/apis/sync-all",
  "/admin/settings/apis/temporary-number-coding-sites/simulate",
  "/admin/settings/apis/{id}",
  "/admin/settings/apis/{id}/sync",
  "/admin/settings/currencies",
  "/admin/settings/currencies/{id}",
  "/admin/settings/payment-codes",
  "/admin/settings/payment-codes/journal",
  "/admin/settings/payment-codes/{id}",
  "/admin/settings/payment-gateways",
  "/admin/settings/payment-gateways/{id}",
  "/admin/settings/pricing-simulation/calculate",
  "/admin/stocks/categories",
  "/admin/stocks/categories/{id}",
  "/admin/stocks/product-groups",
  "/admin/stocks/product-requirements",
  "/admin/stocks/product-requirements/{id}",
  "/admin/stocks/products",
  "/admin/stocks/products/import",
  "/admin/stocks/products/import/preview",
  "/admin/stocks/products/{id}",
  "/admin/stocks/products/{id}/api-connections",
  "/admin/stocks/products/{id}/api-connections/{connectionId}",
  "/admin/stocks/products/{id}/api-connections/{connectionId}/activate",
  "/admin/stocks/promotions",
  "/admin/stocks/promotions/usages",
  "/admin/stocks/promotions/{id}",
  "/admin/stocks/service-groups",
  "/admin/stocks/service-groups/{id}",
  "/admin/stocks/services",
  "/admin/stocks/services/{id}",
  "/admin/stocks/warehouses",
  "/admin/stocks/warehouses/items",
  "/admin/stocks/warehouses/items/import",
  "/admin/stocks/warehouses/{id}",
  "/admin/system/health",
  "/admin/system/metrics",
  "/admin/uploads",
  "/admin/uploads/{id}",
  "/admin/users",
  "/admin/users/{id}",
  "/admin/users/{id}/roles",
  "/admin/users/{id}/status",
  "/auth/2fa/disable",
  "/auth/2fa/enable",
  "/auth/2fa/setup",
  "/auth/2fa/verify-login",
  "/auth/change-password",
  "/auth/forgot-password",
  "/auth/login",
  "/auth/logout",
  "/auth/refresh-token",
  "/auth/register",
  "/auth/resend-verification",
  "/auth/reset-password",
  "/auth/verify-email",
  "/i18n/languages",
  "/i18n/languages/{code}",
  "/notifications",
  "/notifications/read-all",
  "/notifications/unread-count",
  "/notifications/{id}",
  "/notifications/{id}/read",
  "/payment-codes/redeem",
  "/settings/app",
  "/uploads",
  "/uploads/avatar",
  "/uploads/{id}",
  "/users/me",
  "/users/me/avatar",
  "/users/me/password",
  "/users/me/sessions",
  "/users/me/sessions/{id}"
] as const satisfies readonly ApiContractPath[];

export type ApiContractResponse = ApiResponse<unknown>;
export type ApiContractResponses = Record<ApiContractPath, ApiContractResponse>;
