export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh-token',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/users/me',
  },
  USERS: {
    ME: '/users/me',
    AVATAR: '/users/me/avatar',
    PASSWORD: '/users/me/password',
    SESSIONS: '/users/me/sessions',
    SESSION_BY_ID: (id: string) => `/users/me/sessions/${id}`,
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    USER_BY_ID: (id: string) => `/admin/users/${id}`,
    USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    USER_ROLES: (id: string) => `/admin/users/${id}/roles`,
    ROLES: '/admin/roles',
    ROLE_BY_ID: (id: string) => `/admin/roles/${id}`,
    PERMISSIONS: '/admin/permissions',
    AUDIT_LOGS: '/admin/audit-logs',
    SESSIONS: '/admin/sessions',
    SESSION_BY_ID: (id: string) => `/admin/sessions/${id}`,
    UPLOADS: '/admin/uploads',
    UPLOAD_BY_ID: (id: string) => `/admin/uploads/${id}`,
    HEALTH: '/admin/system/health',
    METRICS: '/admin/system/metrics',
    LANGUAGES: '/admin/languages',
    LANGUAGE_TEMPLATE: '/admin/languages/template',
  },
  I18N: {
    LANGUAGES: '/i18n/languages',
    LANGUAGE_BY_CODE: (code: string) => `/i18n/languages/${code}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE_BY_ID: (id: string) => `/notifications/${id}`,
  },
  UPLOADS: {
    AVATAR: '/uploads/avatar',
    LIST: '/uploads',
    DELETE_BY_ID: (id: string) => `/uploads/${id}`,
  },
};
