export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    TWO_FACTOR_VERIFY_LOGIN: '/auth/2fa/verify-login',
    TWO_FACTOR_SETUP: '/auth/2fa/setup',
    TWO_FACTOR_ENABLE: '/auth/2fa/enable',
    TWO_FACTOR_DISABLE: '/auth/2fa/disable',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh-token',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/users/me',
  },
  USERS: {
    ME: '/users/me',
    AVATAR: '/users/me/avatar',
    PASSWORD: '/users/me/password',
    SESSIONS: '/users/me/sessions',
    SESSION_BY_ID: (id: string) => `/users/me/sessions/${id}`,
    LEVELS: '/users/me/levels',
    FINANCIAL_MOVEMENTS: '/users/me/financial-movements',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    USER_BY_ID: (id: string) => `/admin/users/${id}`,
    USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    USER_ROLES: (id: string) => `/admin/users/${id}/roles`,
    CLIENTS: '/admin/clients',
    CLIENT_FINANCIAL_MOVEMENTS: '/admin/clients/financial-movements',
    CLIENT_SPECIAL_PRICES_ALL: '/admin/clients/special-prices',
    PAYMENTS: '/admin/payments',
    PAYMENT_BY_ID: (id: string) => `/admin/payments/${id}`,
    PAYMENT_APPROVE: (id: string) => `/admin/payments/${id}/approve`,
    PAYMENT_REJECT: (id: string) => `/admin/payments/${id}/reject`,
    PROBLEM_REPORTS: '/admin/problem-reports',
    PROBLEM_REPORT_BY_ID: (id: string) => `/admin/problem-reports/${id}`,
    PROBLEM_REPORT_ASSIGN: (id: string) => `/admin/problem-reports/${id}/assign`,
    PROBLEM_REPORT_STATUS: (id: string) => `/admin/problem-reports/${id}/status`,
    PROBLEM_REPORT_PRIORITY: (id: string) => `/admin/problem-reports/${id}/priority`,
    PROBLEM_REPORT_MESSAGES: (id: string) => `/admin/problem-reports/${id}/messages`,
    CLIENT_BY_ID: (id: string) => `/admin/clients/${id}`,
    CLIENT_DELETE: (id: string) => `/admin/clients/${id}`,
    CLIENT_MOVEMENTS: (id: string) => `/admin/clients/${id}/movements`,
    CLIENT_OPEN_CREDIT: (id: string) => `/admin/clients/${id}/open-credit`,
    CLIENT_LEVELS: (id: string) => `/admin/clients/${id}/levels`,
    CLIENT_SPECIAL_PRICES: (id: string) => `/admin/clients/${id}/special-prices`,
    ORDERS: '/admin/orders',
    ORDER_BY_ID: (id: string) => `/admin/orders/${id}`,
    ORDER_TAKE: (id: string) => `/admin/orders/${id}/take`,
    ORDER_COMPLETE: (id: string) => `/admin/orders/${id}/complete`,
    ORDER_FAIL: (id: string) => `/admin/orders/${id}/fail`,
    ORDER_SWITCH_API: (id: string) => `/admin/orders/${id}/switch-api`,
    ORDER_CANCEL: (id: string) => `/admin/orders/${id}/cancel`,
    ROLES: '/admin/roles',
    ROLE_BY_ID: (id: string) => `/admin/roles/${id}`,
    PERMISSIONS: '/admin/permissions',
    AUDIT_LOGS: '/admin/audit-logs',
    SESSIONS: '/admin/sessions',
    SESSION_BY_ID: (id: string) => `/admin/sessions/${id}`,
    UPLOADS: '/admin/uploads',
    UPLOAD_BY_ID: (id: string) => `/admin/uploads/${id}`,
    HEALTH: '/admin/system/health',
    METRICS: '/admin/system/metrics',
    LANGUAGES: '/admin/languages',
    LANGUAGE_TEMPLATE: '/admin/languages/template',
    STOCK_SERVICES: '/admin/stocks/services',
    STOCK_SERVICE_BY_ID: (id: string) => `/admin/stocks/services/${id}`,
    STOCK_SERVICE_GROUPS: '/admin/stocks/service-groups',
    STOCK_SERVICE_GROUP_BY_ID: (id: string) => `/admin/stocks/service-groups/${id}`,
    STOCK_CATEGORIES: '/admin/stocks/categories',
    STOCK_CATEGORY_BY_ID: (id: string) => `/admin/stocks/categories/${id}`,
    STOCK_PRODUCTS: '/admin/stocks/products',
    STOCK_PRODUCT_BY_ID: (id: string) => `/admin/stocks/products/${id}`,
    STOCK_PRODUCT_API_CONNECTIONS: (productId: string) => `/admin/stocks/products/${productId}/api-connections`,
    STOCK_PRODUCTS_IMPORT_PREVIEW: '/admin/stocks/products/import/preview',
    STOCK_PRODUCTS_IMPORT: '/admin/stocks/products/import',
    STOCK_PRODUCT_REQUIREMENTS: '/admin/stocks/product-requirements',
    STOCK_PRODUCT_REQUIREMENT_BY_ID: (id: string) => `/admin/stocks/product-requirements/${id}`,
    STOCK_PRODUCT_GROUPS: '/admin/stocks/product-groups',
    STOCK_WAREHOUSES: '/admin/stocks/warehouses',
    STOCK_WAREHOUSE_BY_ID: (id: string) => `/admin/stocks/warehouses/${id}`,
    STOCK_WAREHOUSE_ITEMS: '/admin/stocks/warehouses/items',
    STOCK_PROMOTIONS: '/admin/stocks/promotions',
    STOCK_PROMOTION_USAGES: '/admin/stocks/promotions/usages',
    STOCK_PROMOTION_BY_ID: (id: string) => `/admin/stocks/promotions/${id}`,
    SETTINGS_CURRENCIES: '/admin/settings/currencies',
    SETTINGS_CURRENCY_BY_ID: (id: string) => `/admin/settings/currencies/${id}`,
    SETTINGS_APP: '/settings/app',
    SETTINGS_APIS: '/admin/settings/apis',
    SETTINGS_API_BY_ID: (id: string) => `/admin/settings/apis/${id}`,
    SETTINGS_API_SYNC: (id: string) => `/admin/settings/apis/${id}/sync`,
    SETTINGS_API_SYNC_ALL: '/admin/settings/apis/sync-all',
    SETTINGS_API_GIFT_CARD_PROVIDERS_SIMULATE: '/admin/settings/apis/gift-card-providers/simulate',
    SETTINGS_API_GIFT_CARD_PROVIDERS_2_SIMULATE: '/admin/settings/apis/gift-card-providers-2/simulate',
    SETTINGS_API_SOCIAL_MEDIA_SERVICE_PROVIDERS_SIMULATE: '/admin/settings/apis/social-media-service-providers/simulate',
    SETTINGS_API_TEMPORARY_NUMBER_CODING_SITES_SIMULATE: '/admin/settings/apis/temporary-number-coding-sites/simulate',
    SETTINGS_PAYMENT_GATEWAYS: '/admin/settings/payment-gateways',
    SETTINGS_PAYMENT_GATEWAY_BY_ID: (id: string) => `/admin/settings/payment-gateways/${id}`,
    SETTINGS_PAYMENT_CODES: '/admin/settings/payment-codes',
    SETTINGS_PAYMENT_CODE_JOURNAL: '/admin/settings/payment-codes/journal',
    SETTINGS_PRICING_SIMULATION_CALCULATE: '/admin/settings/pricing-simulation/calculate',
  },
  PAYMENT_CODES: {
    REDEEM: '/payment-codes/redeem',
  },
  PAYMENTS: {
    BANKS: '/payments/banks',
    LIST: '/payments',
  },
  PROBLEM_REPORTS: {
    LIST: '/problem-reports',
    BY_ID: (id: string) => `/problem-reports/${id}`,
    MESSAGES: (id: string) => `/problem-reports/${id}/messages`,
    CLOSE: (id: string) => `/problem-reports/${id}/close`,
  },
  SHOP: {
    SERVICES: '/shop/services',
    CATEGORIES: '/shop/categories',
    PRODUCT_GROUPS: '/shop/product-groups',
    CATEGORY_ITEMS: '/shop/category-items',
    PRODUCTS: '/shop/products',
    PRODUCT_BY_ID: (id: string) => `/shop/products/${id}`,
    ORDERS: '/shop/orders',
    ORDER_BY_ID: (id: string) => `/shop/orders/${id}`,
  },
  I18N: {
    LANGUAGES: '/i18n/languages',
    LANGUAGE_BY_CODE: (code: string) => `/i18n/languages/${code}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE_BY_ID: (id: string) => `/notifications/${id}`,
  },
  UPLOADS: {
    AVATAR: '/uploads/avatar',
    LIST: '/uploads',
    DELETE_BY_ID: (id: string) => `/uploads/${id}`,
  },
};
