export const queryKeys = {
  auth: {
    me: ['auth', 'me'] as const,
    sessions: ['auth', 'sessions'] as const,
  },
  users: {
    list: ['users', 'list'] as const,
    byId: (id: string) => ['users', id] as const,
  },
  admin: {
    dashboard: ['admin', 'dashboard'] as const,
    users: ['admin', 'users'] as const,
    clients: ['admin', 'clients'] as const,
    orders: ['admin', 'orders'] as const,
    problemReports: ['admin', 'problem-reports'] as const,
    roles: ['admin', 'roles'] as const,
    permissions: ['admin', 'permissions'] as const,
    auditLogs: ['admin', 'audit-logs'] as const,
    sessions: ['admin', 'sessions'] as const,
    uploads: ['admin', 'uploads'] as const,
    health: ['admin', 'health'] as const,
    metrics: ['admin', 'metrics'] as const,
    languages: ['admin', 'languages'] as const,
    stockServices: ['admin', 'stocks', 'services'] as const,
    stockServiceGroups: ['admin', 'stocks', 'service-groups'] as const,
    stockCategories: ['admin', 'stocks', 'categories'] as const,
    stockProducts: ['admin', 'stocks', 'products'] as const,
    stockProductApiConnections: ['admin', 'stocks', 'product-api-connections'] as const,
    stockProductRequirements: ['admin', 'stocks', 'product-requirements'] as const,
    stockProductGroups: ['admin', 'stocks', 'product-groups'] as const,
    stockWarehouses: ['admin', 'stocks', 'warehouses'] as const,
    stockWarehouseItems: ['admin', 'stocks', 'warehouse-items'] as const,
    stockPromotions: ['admin', 'stocks', 'promotions'] as const,
    stockPromotionUsages: ['admin', 'stocks', 'promotion-usages'] as const,
    settingsApp: ['settings', 'app'] as const,
    settingsCurrencies: ['admin', 'settings', 'currencies'] as const,
    settingsApis: ['admin', 'settings', 'apis'] as const,
    settingsApiGiftCardProvidersSimulation: ['admin', 'settings', 'apis', 'gift-card-providers-simulation'] as const,
    settingsPaymentGateways: ['admin', 'settings', 'payment-gateways'] as const,
    settingsPaymentCodes: ['admin', 'settings', 'payment-codes'] as const,
    settingsPaymentCodeJournal: ['admin', 'settings', 'payment-code-journal'] as const,
    settingsPricingSimulation: ['admin', 'settings', 'pricing-simulation'] as const,
  },
  i18n: {
    languages: ['i18n', 'languages'] as const,
  },
  notifications: {
    list: ['notifications', 'list'] as const,
    unreadCount: ['notifications', 'unread-count'] as const,
  },
  shop: {
    services: ['shop', 'services'] as const,
    categories: ['shop', 'categories'] as const,
    productGroups: ['shop', 'product-groups'] as const,
    categoryItems: ['shop', 'category-items'] as const,
    products: ['shop', 'products'] as const,
    orders: ['shop', 'orders'] as const,
  },
  problemReports: {
    list: ['problem-reports', 'list'] as const,
    byId: (id: string) => ['problem-reports', id] as const,
  },
} as const;
